### ISSUE TITLE
Add mod support

### ISSUE THREAD

**Issue by amak79** [flathub/org.dhewm3.Dhewm3#3]
Would it be possible to add dhewm3 [mod](https://dhewm3.org/mods.html) support? The source for each officially supported mod can be found [here](https://github.com/dhewm/dhewm3-sdk) in their respective branches.

I've successfully tested [The Lost Mission](https://dhewm3.org/mods.html#the-lost-mission) mod (part of Doom 3 BFG Edition) with the pre-built binary by copying `d3le.so` to `/var/lib/flatpak/app/org.dhewm3.Dhewm3/current/active/files/lib/dhewm3`. The only problem with this approach is that I would need to copy over the mod `.so` files each time the dhewm3 flatpak was updated, unless they can be installed somewhere in `~/.var/app/org.dhewm3.Dhewm3`.

**Comment by Eonfge** [comment]
I totally agree! It would be great to have some mods pre-compiled.I even had a version with Denton Mod pre-compiled.

Sadly, there are some hurdles...
- https://github.com/dhewm/dhewm3/issues/390
- https://github.com/dhewm/dhewm3/issues/391

Right now, there are some issues in the code that make running Dhewm 3 with mods a big pain. Put bluntly, I'll not bundle mods until these issues are released upstream. Sorry for the inconvenience right now, but hopefully we'll soon have a new version of Dhewm 3 will full mod support.

**Comment by Eonfge** [comment]
I have not forgotten you! Sadly, no upstream release yet. Once upstream has a new release, I'll package some mods. I did actually finish the entire game with Denton Mod, but then you'll have to manually build the flatpak using custom patches.

**Comment by Eonfge** [comment]
I have great news, Dhewm 3 Flatpak will now support mods:
- https://github.com/flathub/org.dhewm3.Dhewm3/pull/5

I've included 3 mods for now, for testing purposes:
- denton
- lost mission
- libre coop

If you can give this test version a spin, that would be much appreciated.

@DanielGibson Your work is paying off!

**Comment by amak79** [comment]
I've successfully run The Lost Mission with:
```
$ flatpak run --branch=test --arch=x86_64 --command=dhewm3 org.dhewm3.Dhewm3 +set fs_game_base d3xp +set fs_game d3le
```
If I start Dhewm3 with:
```
$ flatpak run --branch=test --arch=x86_64 --command=dhewm3.sh org.dhewm3.Dhewm3
```
and at the main menu select Mods->The Lost Mission I get a `SIGABRT` and `SIGSEGV`. I don't know if starting mods that way is supported, but it also happens with the stable branch.

I also noticed that the mod `.so` files are installed in `files/bin` rather than `files/lib/dhewm3`. Not sure if that matters.

Do you plan on providing desktop menu files for the mods? I persoanlly use the following for The Lost Mission:

```
[Desktop Entry]
Comment=dhewm 3 is a Doom 3 GPL source port
Categories=Game;Shooter;
Exec=/usr/bin/flatpak run --branch=test --arch=x86_64 --command=dhewm3 org.dhewm3.Dhewm3 +set fs_game_base d3xp +set fs_game d3le
Icon=org.dhewm3.Dhewm3
Name=Dhewm3 LE
StartupNotify=true
Terminal=false
Type=Application
Keywords=doom;first;person;shooter;dark;singleplayer;multiplayer;
X-Flatpak=org.dhewm3.Dhewm3
```

**Comment by Eonfge** [comment]
> If I start Dhewm3 with:
> 
> ```
> $ flatpak run --branch=test --arch=x86_64 --command=dhewm3.sh org.dhewm3.Dhewm3
> ```
> 
> and at the main menu select Mods->The Lost Mission I get a `SIGABRT` and `SIGSEGV`. I don't know if starting mods that way is supported, but it also happens with the stable branch.

You'll have to report this upstream, as I'm not directly involved in the development of Dhewm3. I just aid in the distribution.

> I also noticed that the mod .so files are installed in files/bin rather than files/lib/dhewm3. Not sure if that matters.

Neither do I. I can try putting them in /lib/ to see if it matters.

> Do you plan on providing desktop menu files for the mods?

I don't know... So far, I haven't thought this completely through. There are 5 Mods and 2 Total Conversions, and I don't want to add 9 desktop icons to the system just for that. Besides, I can't ship the mod content so users will have to go manually to their user folder and add the right files.

Perhaps we should just solve these questions as they come up: Please inform upstream about the problems with the Mod Selector, then I'll look into the /lib/ folder and I'll add the other .so files. I tried a bit of Denton Mod so far, and it all worked fine.

**Comment by amak79** [comment]
> There are 5 Mods and 2 Total Conversions, and I don't want to add 9 desktop icons to the system just for that. Besides, I can't ship the mod content so users will have to go manually to their user folder and add the right files.

Makes sense. Users would almost certainly attempt to run the mods after seeing the menus entries but they would fail to run.

> Perhaps we should just solve these questions as they come up: Please inform upstream about the problems with the Mod Selector, then I'll look into the /lib/ folder and I'll add the other .so files. I tried a bit of Denton Mod so far, and it all worked fine.

I will report the mod selector issue upstream.

Thank you very much for working on this.

**Comment by amak79** [comment]
The mod selector issue has been [reported](https://github.com/dhewm/dhewm3/issues/458) upstream and a fix committed. Can you please push a new test build so I can test the fix?

**Comment by Eonfge** [comment]
New build coming up:
https://github.com/flathub/org.dhewm3.Dhewm3/pull/5

**Comment by DanielGibson** [comment]
Thanks @Eonfge for providing a new build so soon, and thanks to @amak79 for reporting the bug!

By the way, The Lost Mission still can't be started via Mod-Menu, because it's based on Resurrection of Evil (RoE/d3xp).
The mod menu only properly supports mods that don't need d3xp (except for d3xp itself) - or any other mod, for that matter.
The Lost Mission must be started with `./dhewm3 +set fs_game d3le +set fs_game_base d3xp` - the special thing here is `fs_game_base` which the mod menu can't set, because there is no standardized way for mods to communicate what other mod (fs_game_base) they're using - id maybe could've added something for this to the format of mod/description.txt, but they didn't.

**Comment by Eonfge** [comment]
@DanielGibson No problem, Just glad to help.

> id maybe could've added something for this to the format of mod/description.txt, but they didn't.

Could we not just add a second button? Besides 'Load Mod' you could add a 'Load Mod + Exp' and then add the `+set fs_game_base d3xp` in the app. It's not a very elegant solution, but it at least gives users a way to work around the issue without falling back to the command-line.

**Comment by DanielGibson** [comment]
Unfortunately, adding buttons isn't that easy either, because that would require shipping a modified main menu (and not just for the main game but for every mod that has a mods menu, I guess?)

**Comment by Eonfge** [comment]
Ooh. That's a lot of work and hard to keep working... Okey, second idea: Would it be possible to just list all mods twice? 'Denton' and 'Denton + Expansion'? My guess is that users won't switch mods very often so I would only add that logic to the base game. In the end you have the same result but you won't have to change any complex UI things.

In the end... perhaps this isn't really an issue worth solving. It has been like this for the past 15 years and it's not like Doom 3 is such a hot property.

**Comment by DanielGibson** [comment]
>  Would it be possible to just list all mods twice? 'Denton' and 'Denton + Expansion'?

That would only confuse people, thinking that both variants work and maybe let you play either the base game levels or the d3xp levels (esp. with a mod like Denton that uses the original levels)

I might hardcode special-cases in the mod loading code for some mods that are known to need d3xp - but if someone tries another mod that also needs d3xp and it doesn't work that can again cause confusion..

**Comment by Eonfge** [comment]
> I might hardcode special-cases in the mod loading code for some mods that are known to need d3xp - but if someone tries another mod that also needs d3xp and it doesn't work that can again cause confusion..

This might work well for the limited amount of mods that Dhewm3 actually supports. Since there are only 7 or so mods, we could save ourselves a lot of hassle, hardcode the few that need it and call it a day. If people really want to play Doom 3 RoE in Coop, they might have to check the readme anyway since installing the mod data is still not trivial.

**Comment by DanielGibson** [comment]
True - though it's possible that there are mods that don't need their own DLL (so they should work with dhewm3 without any special support) and still use `fs_game_base`.
No idea if that's actually the case, I don't play many mods

**Comment by Eonfge** [comment]
My guess? Let's fix it for The Last Mission and call it quit for now... see if somebody else ever brings this up because I can't see this being much of a thing.

**Comment by amak79** [comment]
@Eonfge Thank you for the test build. I can confirm that the mod selector issue has been fixed.

**Comment by amak79** [comment]
@DanielGibson Perhaps adding a note about not being able load the Lost Mission via the Mods menu to the [mods](https://dhewm3.org/mods.html) page will help.

**Comment by DanielGibson** [comment]
I just implemented a special case for the mod menu to set `fs_game_base d3xp` if the mod to be loaded is either "d3le" or "librecoopd3xp".

**Comment by Eonfge** [comment]
Made an update to the draft: https://github.com/flathub/org.dhewm3.Dhewm3/pull/5

**Comment by amak79** [comment]
I tried the test build and The Lost Mission can now be loaded via the mods menu. Thank you.

**Comment by Eonfge** [comment]
I have finished all of The Lost Mission with RC2. So that all seems to be stable and good to go.

As for TLM... It's about as good as Doom 3 can be with its slow movement, stodgy arsenal and poor monster design.

**Comment by Eonfge** [comment]
Whoho, 1.5.2 is out! I'll be going through all the steps, and it will be released in an hour or two. Including mod support and such. \

With some of the bug-fixes related to Wayland, I'll also re-enable Wayland support. I tested this on my machine and everything seemed to run fine.

**Comment by DanielGibson** [comment]
Great, thanks! :)

**Comment by Eonfge** [comment]
@amak79 Thanks for reporting this issue initially and thanks @DanielGibson for collaborating and helping. I'm closing this issue now, and I hope that we all get to enjoy a save and productive shift at the UAC Research Facility.
